# Muni configuration file
# Authored by bobbshields
#
# Note: If something is commented out (#), it is done on purpose by the dev
#        It is likely that the functionality is not yet added to Muni
#
#################################################################
# Descriptions of certain nodes
#####
# 
#################################################################

config_version: .01
use_metrics: true
debug: false
sql_debug: false
database:
    use-mysql: false  
    host: localhost
    database: minecraft
    user: minecraft
    password: password
    prefix: news_